# RF-DETR instance segmentation (COCO v2)

Train `RFDETRSegSmall` on Roboflow-exported COCO. Activate conda env **`projeto_placentas`** before running.

**4GB VRAM:** defaults use `batch_size=1`, `grad_accum_steps=16`, `gradient_checkpointing=True`, `resolution=560`. If CUDA OOM, lower `resolution` (must stay divisible by 14).

Run cells **top to bottom** (paths cell must run before train and inference).

In [1]:
import torch
from importlib.metadata import version, PackageNotFoundError
from rfdetr import RFDETRSegSmall

try:
    _rf_ver = version("rfdetr")
except PackageNotFoundError:
    _rf_ver = "unknown"
print(f"rfdetr: {_rf_ver}")
print(f"torch: {torch.__version__}")
print(f"cuda available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"device: {torch.cuda.get_device_name(0)}")

d:\miniconda3\envs\projeto_placentas\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

rfdetr: 1.6.2
torch: 2.5.1+cu121
cuda available: True
device: NVIDIA GeForce GTX 1650 SUPER

In [2]:
from pathlib import Path

REPO_ROOT = Path(r"D:\projeto_placentas_clayton\dev\projeto-placentas").resolve()
V2_RF_DETR = REPO_ROOT / "v2_rf_detr"
DATASET_DIR = Path(r"D:\projeto_placentas_clayton\dataset_v2_coco_rf_detr").resolve()

OUTPUT_RUN = "seg_small_v1"
OUTPUT_DIR = (V2_RF_DETR / "runs" / OUTPUT_RUN).resolve()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("DATASET_DIR:", DATASET_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)

DATASET_DIR: D:\projeto_placentas_clayton\dataset_v2_coco_rf_detr
OUTPUT_DIR: D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1

In [3]:
import json
from collections import Counter

def summarize_split(split: str) -> None:
    p = DATASET_DIR / split / "_annotations.coco.json"
    if not p.is_file():
        print(f"missing: {p}")
        return
    data = json.loads(p.read_text(encoding="utf-8"))
    cats = {c["id"]: c["name"] for c in data.get("categories", [])}
    anns = data.get("annotations", [])
    seg_n = sum(1 for a in anns if a.get("segmentation"))
    cat_ids = Counter(a.get("category_id") for a in anns)
    print(f"[{split}] images: {len(data.get('images', []))}  annotations: {len(anns)}  with segmentation: {seg_n}")
    print(f"[{split}] category_id counts: {dict(cat_ids)}")
    print(f"[{split}] categories: {cats}")

summarize_split("train")
summarize_split("valid")

[train] images: 153  annotations: 4753  with segmentation: 4752
[train] category_id counts: {1: 4753}
[train] categories: {0: 'objects', 1: 'microcotiledone'}
[valid] images: 27  annotations: 852  with segmentation: 852
[valid] category_id counts: {1: 852}
[valid] categories: {0: 'objects', 1: 'microcotiledone'}

In [4]:
model = RFDETRSegSmall()

model.train(
    dataset_dir=str(DATASET_DIR),
    output_dir=str(OUTPUT_DIR),
    epochs=120,
    batch_size=1,
    grad_accum_steps=16,
    lr=1e-4,
    gradient_checkpointing=True,
    resolution=560,
    early_stopping=True,
    early_stopping_patience=30,
    progress_bar=True,
    seed=0,
)

[2026-03-28 18:23:41] [INFO] rf-detr - File rf-detr-seg-small.pt already exists with correct MD5 hash.

[2026-03-28 18:23:41] [WARNING] rf-detr - Using a different number of positional encodings than DINOv2, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.
[2026-03-28 18:23:41] [WARNING] rf-detr - Using patch size 12 instead of 14, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.

[2026-03-28 18:23:41] [INFO] rf-detr - File rf-detr-seg-small.pt already exists with correct MD5 hash.

[2026-03-28 18:23:51] [WARNING] rf-detr - Using a different number of positional encodings than DINOv2, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.
[2026-03-28 18:23:51] [WARNING] rf-detr - Using patch size 12 instead of 14, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.

[2026-03-28 18:23:51] [INFO] rf-detr - File rf-detr-seg-small.pt already exists with correct MD5 hash.

[2026-03-28 18:23:52] [WARNING] rf-detr - TensorBoard logging disabled: Neither `tensorboard` nor `tensorboardX` is available. Try `pip install`ing either.
Requirement 'tensorboardX' not met. HINT: Try running `pip install -U 'tensorboardX'`
Requirement 'tensorboard' not met. HINT: Try running `pip install -U 'tensorboard'`. Install with: pip install tensorboard
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

[2026-03-28 18:23:52] [INFO] rf-detr - Building Roboflow train dataset with square resize at resolution 384
[2026-03-28 18:23:52] [INFO] rf-detr - Using multi-scale training with square resize and scales: [504]
[2026-03-28 18:23:52] [INFO] rf-detr - Built 1 Albumentations transforms from config
[2026-03-28 18:23:52] [INFO] rf-detr - Built 1 Albumentations transforms from config

d:\miniconda3\envs\projeto_placentas\lib\site-packages\lightning_fabric\loggers\csv_logs.py:268: Experiment logs directory D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!

loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
[2026-03-28 18:23:52] [INFO] rf-detr - Building Roboflow val dataset with square resize at resolution 384
[2026-03-28 18:23:52] [INFO] rf-detr - Using multi-scale training with square resize and scales: [504]
[2026-03-28 18:23:52] [INFO] rf-detr - Built 1 Albumentations transforms from config
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!

d:\miniconda3\envs\projeto_placentas\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1 exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loading `train_dataloader` to estimate number of stepping batches.
d:\miniconda3\envs\projeto_placentas\lib\site-packages\pytorch_lightning\utilities\model_summary\model_summary.py:242: Precision bf16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.

┏━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name        ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model       │ LWDETR       │ 33.7 M │ train │     0 │
│ 1 │ criterion   │ SetCriterion │      0 │ train │     0 │
│ 2 │ postprocess │ PostProcess  │      0 │ train │     0 │
└───┴─────────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 33.7 M
Non-trainable params: 0
Total params: 33.7 M
Total estimated model params size (MB): 134
Modules in train mode: 513
Modules in eval mode: 0
Total FLOPs: 0

Seed set to 0

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

`use_return_dict` is deprecated! Use `return_dict` instead!

Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:04<00:00,  0.47it/s]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.0134 │ 0.0149 │ 0.0149 │ 0.0214 │ 0.0444 │ 0.3333 │ 0.0238 │ 0.0134 │ 0.0149 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.0134 │ 0.0214 │ 0.0444 │    0.3333 │ 0.0238 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

[2026-03-28 18:24:31] [INFO] rf-detr - Best EMA mAP improved to 0.0134 (epoch 0)
Epoch 0: 100%|██████████| 153/153 [03:03<00:00,  0.83it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7240 │ 0.8861 │ 0.8084 │ 0.8042 │ 0.8701 │ 0.9008 │ 0.8415 │ 0.7030 │ 0.8972 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7240 │ 0.8042 │ 0.8701 │    0.9008 │ 0.8415 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 0: 100%|██████████| 153/153 [03:22<00:00,  0.76it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=8.060, val/mAP_50_95=0.724, val/mAP_50=0.886, val/ema_mAP_50_95=0.725, val/F1=0.870]

Metric __rfdetr_effective_map__ improved. New best score: 0.725

[2026-03-28 18:27:53] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 0)
[2026-03-28 18:27:54] [INFO] rf-detr - Best EMA mAP improved to 0.7249 (epoch 0)
Epoch 1: 100%|██████████| 153/153 [03:35<00:00,  0.71it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=8.060, val/mAP_50_95=0.724, val/mAP_50=0.886, val/ema_mAP_50_95=0.725, val/F1=0.870, train/loss=11.90]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7589 │ 0.8980 │ 0.8170 │ 0.8358 │ 0.8774 │ 0.8901 │ 0.8650 │ 0.7099 │ 0.9077 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7589 │ 0.8358 │ 0.8774 │    0.8901 │ 0.8650 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 1: 100%|██████████| 153/153 [03:53<00:00,  0.66it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.480, val/mAP_50_95=0.759, val/mAP_50=0.898, val/ema_mAP_50_95=0.761, val/F1=0.877, train/loss=11.90]

Metric __rfdetr_effective_map__ improved by 0.036 >= min_delta = 0.001. New best score: 0.761

[2026-03-28 18:32:11] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 1)
[2026-03-28 18:32:11] [INFO] rf-detr - Best EMA mAP improved to 0.7610 (epoch 1)
Epoch 2: 100%|██████████| 153/153 [03:13<00:00,  0.79it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.480, val/mAP_50_95=0.759, val/mAP_50=0.898, val/ema_mAP_50_95=0.761, val/F1=0.877, train/loss=8.790]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7796 │ 0.9139 │ 0.8500 │ 0.8488 │ 0.8871 │ 0.9183 │ 0.8580 │ 0.7365 │ 0.9218 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7796 │ 0.8488 │ 0.8871 │    0.9183 │ 0.8580 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 2: 100%|██████████| 153/153 [03:30<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.160, val/mAP_50_95=0.780, val/mAP_50=0.914, val/ema_mAP_50_95=0.781, val/F1=0.887, train/loss=8.790]

Metric __rfdetr_effective_map__ improved by 0.020 >= min_delta = 0.001. New best score: 0.781

[2026-03-28 18:35:57] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 2)
[2026-03-28 18:35:57] [INFO] rf-detr - Best EMA mAP improved to 0.7809 (epoch 2)
Epoch 3: 100%|██████████| 153/153 [02:45<00:00,  0.92it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.160, val/mAP_50_95=0.780, val/mAP_50=0.914, val/ema_mAP_50_95=0.781, val/F1=0.887, train/loss=8.290]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7867 │ 0.9169 │ 0.8524 │ 0.8549 │ 0.8825 │ 0.9276 │ 0.8415 │ 0.7241 │ 0.9191 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7867 │ 0.8549 │ 0.8825 │    0.9276 │ 0.8415 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 3: 100%|██████████| 153/153 [03:03<00:00,  0.83it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.990, val/mAP_50_95=0.787, val/mAP_50=0.917, val/ema_mAP_50_95=0.787, val/F1=0.882, train/loss=8.290]

Metric __rfdetr_effective_map__ improved by 0.006 >= min_delta = 0.001. New best score: 0.787

[2026-03-28 18:39:13] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 3)
[2026-03-28 18:39:13] [INFO] rf-detr - Best EMA mAP improved to 0.7871 (epoch 3)
Epoch 4: 100%|██████████| 153/153 [03:30<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.990, val/mAP_50_95=0.787, val/mAP_50=0.917, val/ema_mAP_50_95=0.787, val/F1=0.882, train/loss=7.900]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7919 │ 0.9221 │ 0.8597 │ 0.8580 │ 0.8836 │ 0.9189 │ 0.8509 │ 0.7633 │ 0.9281 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7919 │ 0.8580 │ 0.8836 │    0.9189 │ 0.8509 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 4: 100%|██████████| 153/153 [03:49<00:00,  0.67it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.630, val/mAP_50_95=0.792, val/mAP_50=0.922, val/ema_mAP_50_95=0.795, val/F1=0.884, train/loss=7.900]

Metric __rfdetr_effective_map__ improved by 0.008 >= min_delta = 0.001. New best score: 0.795

[2026-03-28 18:43:11] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 4)
[2026-03-28 18:43:11] [INFO] rf-detr - Best EMA mAP improved to 0.7951 (epoch 4)
Epoch 5: 100%|██████████| 153/153 [03:16<00:00,  0.78it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.630, val/mAP_50_95=0.792, val/mAP_50=0.922, val/ema_mAP_50_95=0.795, val/F1=0.884, train/loss=7.440]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7896 │ 0.9187 │ 0.8516 │ 0.8609 │ 0.8899 │ 0.8926 │ 0.8873 │ 0.7331 │ 0.9260 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7896 │ 0.8609 │ 0.8899 │    0.8926 │ 0.8873 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 6: 100%|██████████| 153/153 [03:49<00:00,  0.67it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.850, val/mAP_50_95=0.790, val/mAP_50=0.919, val/ema_mAP_50_95=0.786, val/F1=0.890, train/loss=7.460]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7926 │ 0.9222 │ 0.8570 │ 0.8586 │ 0.8969 │ 0.9167 │ 0.8779 │ 0.7571 │ 0.9306 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7926 │ 0.8586 │ 0.8969 │    0.9167 │ 0.8779 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 6: 100%|██████████| 153/153 [04:07<00:00,  0.62it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.760, val/mAP_50_95=0.793, val/mAP_50=0.922, val/ema_mAP_50_95=0.797, val/F1=0.897, train/loss=7.460]

Metric __rfdetr_effective_map__ improved by 0.002 >= min_delta = 0.001. New best score: 0.797

[2026-03-28 18:51:40] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 6)
[2026-03-28 18:51:40] [INFO] rf-detr - Best EMA mAP improved to 0.7970 (epoch 6)
Epoch 7: 100%|██████████| 153/153 [03:37<00:00,  0.70it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.760, val/mAP_50_95=0.793, val/mAP_50=0.922, val/ema_mAP_50_95=0.797, val/F1=0.897, train/loss=7.190]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8014 │ 0.9228 │ 0.8691 │ 0.8653 │ 0.8897 │ 0.8944 │ 0.8850 │ 0.7553 │ 0.9281 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8014 │ 0.8653 │ 0.8897 │    0.8944 │ 0.8850 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 7: 100%|██████████| 153/153 [03:55<00:00,  0.65it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.530, val/mAP_50_95=0.801, val/mAP_50=0.923, val/ema_mAP_50_95=0.802, val/F1=0.890, train/loss=7.190]

Metric __rfdetr_effective_map__ improved by 0.005 >= min_delta = 0.001. New best score: 0.802

[2026-03-28 18:55:45] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 7)
[2026-03-28 18:55:45] [INFO] rf-detr - Best EMA mAP improved to 0.8024 (epoch 7)
Epoch 8: 100%|██████████| 153/153 [03:28<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.530, val/mAP_50_95=0.801, val/mAP_50=0.923, val/ema_mAP_50_95=0.802, val/F1=0.890, train/loss=7.150]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7918 │ 0.9164 │ 0.8551 │ 0.8602 │ 0.8895 │ 0.9002 │ 0.8791 │ 0.7549 │ 0.9187 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7918 │ 0.8602 │ 0.8895 │    0.9002 │ 0.8791 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 9: 100%|██████████| 153/153 [03:29<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.670, val/mAP_50_95=0.792, val/mAP_50=0.916, val/ema_mAP_50_95=0.789, val/F1=0.890, train/loss=7.000]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8008 │ 0.9179 │ 0.8564 │ 0.8671 │ 0.8905 │ 0.8984 │ 0.8826 │ 0.7515 │ 0.9239 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8008 │ 0.8671 │ 0.8905 │    0.8984 │ 0.8826 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 9: 100%|██████████| 153/153 [03:47<00:00,  0.67it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.640, val/mAP_50_95=0.801, val/mAP_50=0.918, val/ema_mAP_50_95=0.803, val/F1=0.890, train/loss=7.000][2026-03-28 19:03:34] [INFO] rf-detr - Best EMA mAP improved to 0.8028 (epoch 9)
Epoch 10: 100%|██████████| 153/153 [03:31<00:00,  0.72it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.640, val/mAP_50_95=0.801, val/mAP_50=0.918, val/ema_mAP_50_95=0.803, val/F1=0.890, train/loss=6.790]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8044 │ 0.9216 │ 0.8660 │ 0.8696 │ 0.8988 │ 0.9068 │ 0.8908 │ 0.7641 │ 0.9287 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8044 │ 0.8696 │ 0.8988 │    0.9068 │ 0.8908 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 10: 100%|██████████| 153/153 [03:49<00:00,  0.67it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.540, val/mAP_50_95=0.804, val/mAP_50=0.922, val/ema_mAP_50_95=0.807, val/F1=0.899, train/loss=6.790]

Metric __rfdetr_effective_map__ improved by 0.004 >= min_delta = 0.001. New best score: 0.807

[2026-03-28 19:07:43] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 10)
[2026-03-28 19:07:43] [INFO] rf-detr - Best EMA mAP improved to 0.8067 (epoch 10)
Epoch 11: 100%|██████████| 153/153 [03:06<00:00,  0.82it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.540, val/mAP_50_95=0.804, val/mAP_50=0.922, val/ema_mAP_50_95=0.807, val/F1=0.899, train/loss=6.810]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7936 │ 0.9129 │ 0.8488 │ 0.8558 │ 0.8985 │ 0.8933 │ 0.9038 │ 0.7590 │ 0.9213 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7936 │ 0.8558 │ 0.8985 │    0.8933 │ 0.9038 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 12: 100%|██████████| 153/153 [02:42<00:00,  0.94it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.660, val/mAP_50_95=0.794, val/mAP_50=0.913, val/ema_mAP_50_95=0.800, val/F1=0.898, train/loss=6.570]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7908 │ 0.9171 │ 0.8552 │ 0.8599 │ 0.8929 │ 0.8857 │ 0.9002 │ 0.7418 │ 0.9184 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7908 │ 0.8599 │ 0.8929 │    0.8857 │ 0.9002 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 13: 100%|██████████| 153/153 [03:28<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.820, val/mAP_50_95=0.791, val/mAP_50=0.917, val/ema_mAP_50_95=0.798, val/F1=0.893, train/loss=6.720]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7837 │ 0.9204 │ 0.8561 │ 0.8506 │ 0.8986 │ 0.9078 │ 0.8897 │ 0.7548 │ 0.9212 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7837 │ 0.8506 │ 0.8986 │    0.9078 │ 0.8897 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 14: 100%|██████████| 153/153 [03:30<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.860, val/mAP_50_95=0.784, val/mAP_50=0.920, val/ema_mAP_50_95=0.801, val/F1=0.899, train/loss=6.470]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7995 │ 0.9232 │ 0.8692 │ 0.8638 │ 0.8955 │ 0.9228 │ 0.8697 │ 0.7541 │ 0.9240 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7995 │ 0.8638 │ 0.8955 │    0.9228 │ 0.8697 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 15: 100%|██████████| 153/153 [03:29<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.550, val/mAP_50_95=0.799, val/mAP_50=0.923, val/ema_mAP_50_95=0.801, val/F1=0.895, train/loss=6.310]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8063 │ 0.9229 │ 0.8722 │ 0.8690 │ 0.8894 │ 0.9274 │ 0.8545 │ 0.7420 │ 0.9218 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8063 │ 0.8690 │ 0.8894 │    0.9274 │ 0.8545 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 15: 100%|██████████| 153/153 [03:47<00:00,  0.67it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.660, val/mAP_50_95=0.806, val/mAP_50=0.923, val/ema_mAP_50_95=0.803, val/F1=0.889, train/loss=6.310][2026-03-28 19:26:08] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 15)
Epoch 16: 100%|██████████| 153/153 [03:12<00:00,  0.80it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.660, val/mAP_50_95=0.806, val/mAP_50=0.923, val/ema_mAP_50_95=0.803, val/F1=0.889, train/loss=6.120]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8081 │ 0.9230 │ 0.8707 │ 0.8704 │ 0.8898 │ 0.9241 │ 0.8580 │ 0.7510 │ 0.9240 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8081 │ 0.8704 │ 0.8898 │    0.9241 │ 0.8580 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 16: 100%|██████████| 153/153 [03:30<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.470, val/mAP_50_95=0.808, val/mAP_50=0.923, val/ema_mAP_50_95=0.808, val/F1=0.890, train/loss=6.120]

Metric __rfdetr_effective_map__ improved by 0.001 >= min_delta = 0.001. New best score: 0.808

[2026-03-28 19:29:49] [INFO] rf-detr - Best regular mAP saved to D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\checkpoint_best_regular.pth (epoch 16)
[2026-03-28 19:29:49] [INFO] rf-detr - Best EMA mAP improved to 0.8079 (epoch 16)
Epoch 17: 100%|██████████| 153/153 [03:38<00:00,  0.70it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.470, val/mAP_50_95=0.808, val/mAP_50=0.923, val/ema_mAP_50_95=0.808, val/F1=0.890, train/loss=6.660]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8009 │ 0.9217 │ 0.8657 │ 0.8698 │ 0.8877 │ 0.8940 │ 0.8815 │ 0.7561 │ 0.9200 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8009 │ 0.8698 │ 0.8877 │    0.8940 │ 0.8815 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 18: 100%|██████████| 153/153 [03:41<00:00,  0.69it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.520, val/mAP_50_95=0.801, val/mAP_50=0.922, val/ema_mAP_50_95=0.798, val/F1=0.888, train/loss=6.650]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7805 │ 0.9036 │ 0.8342 │ 0.8546 │ 0.8982 │ 0.8951 │ 0.9014 │ 0.7356 │ 0.9146 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7805 │ 0.8546 │ 0.8982 │    0.8951 │ 0.9014 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 19: 100%|██████████| 153/153 [02:50<00:00,  0.90it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.060, val/mAP_50_95=0.781, val/mAP_50=0.904, val/ema_mAP_50_95=0.794, val/F1=0.898, train/loss=6.260]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7771 │ 0.9000 │ 0.8335 │ 0.8527 │ 0.8899 │ 0.8787 │ 0.9014 │ 0.7240 │ 0.9104 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7771 │ 0.8527 │ 0.8899 │    0.8787 │ 0.9014 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 20: 100%|██████████| 153/153 [03:17<00:00,  0.77it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.000, val/mAP_50_95=0.777, val/mAP_50=0.900, val/ema_mAP_50_95=0.799, val/F1=0.890, train/loss=6.220]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7934 │ 0.9154 │ 0.8477 │ 0.8610 │ 0.8982 │ 0.8951 │ 0.9014 │ 0.7458 │ 0.9241 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7934 │ 0.8610 │ 0.8982 │    0.8951 │ 0.9014 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 21: 100%|██████████| 153/153 [03:07<00:00,  0.82it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.740, val/mAP_50_95=0.793, val/mAP_50=0.915, val/ema_mAP_50_95=0.796, val/F1=0.898, train/loss=6.180]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7936 │ 0.9178 │ 0.8551 │ 0.8623 │ 0.8926 │ 0.8875 │ 0.8979 │ 0.7453 │ 0.9244 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7936 │ 0.8623 │ 0.8926 │    0.8875 │ 0.8979 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 22: 100%|██████████| 153/153 [03:18<00:00,  0.77it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.570, val/mAP_50_95=0.794, val/mAP_50=0.918, val/ema_mAP_50_95=0.800, val/F1=0.893, train/loss=6.140]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8001 │ 0.9181 │ 0.8690 │ 0.8634 │ 0.8990 │ 0.9398 │ 0.8615 │ 0.7417 │ 0.9242 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8001 │ 0.8634 │ 0.8990 │    0.9398 │ 0.8615 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 23: 100%|██████████| 153/153 [03:21<00:00,  0.76it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.520, val/mAP_50_95=0.800, val/mAP_50=0.918, val/ema_mAP_50_95=0.805, val/F1=0.899, train/loss=6.010]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7970 │ 0.9213 │ 0.8607 │ 0.8633 │ 0.8995 │ 0.9060 │ 0.8932 │ 0.7556 │ 0.9231 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7970 │ 0.8633 │ 0.8995 │    0.9060 │ 0.8932 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 24: 100%|██████████| 153/153 [03:08<00:00,  0.81it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.460, val/mAP_50_95=0.797, val/mAP_50=0.921, val/ema_mAP_50_95=0.805, val/F1=0.900, train/loss=6.040]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.8011 │ 0.9225 │ 0.8676 │ 0.8662 │ 0.8993 │ 0.9129 │ 0.8862 │ 0.7477 │ 0.9191 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.8011 │ 0.8662 │ 0.8993 │    0.9129 │ 0.8862 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 25: 100%|██████████| 153/153 [03:29<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.620, val/mAP_50_95=0.801, val/mAP_50=0.923, val/ema_mAP_50_95=0.806, val/F1=0.899, train/loss=6.050]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7949 │ 0.9180 │ 0.8565 │ 0.8628 │ 0.9076 │ 0.9103 │ 0.9049 │ 0.7502 │ 0.9203 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7949 │ 0.8628 │ 0.9076 │    0.9103 │ 0.9049 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 26: 100%|██████████| 153/153 [03:19<00:00,  0.77it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.630, val/mAP_50_95=0.795, val/mAP_50=0.918, val/ema_mAP_50_95=0.805, val/F1=0.908, train/loss=5.820]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7974 │ 0.9147 │ 0.8556 │ 0.8654 │ 0.8999 │ 0.8973 │ 0.9026 │ 0.7434 │ 0.9194 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7974 │ 0.8654 │ 0.8999 │    0.8973 │ 0.9026 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 27: 100%|██████████| 153/153 [03:47<00:00,  0.67it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.780, val/mAP_50_95=0.797, val/mAP_50=0.915, val/ema_mAP_50_95=0.803, val/F1=0.900, train/loss=5.840]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7963 │ 0.9203 │ 0.8551 │ 0.8612 │ 0.9039 │ 0.9077 │ 0.9002 │ 0.7511 │ 0.9227 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7963 │ 0.8612 │ 0.9039 │    0.9077 │ 0.9002 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 28: 100%|██████████| 153/153 [03:09<00:00,  0.81it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.540, val/mAP_50_95=0.796, val/mAP_50=0.920, val/ema_mAP_50_95=0.803, val/F1=0.904, train/loss=6.080]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7907 │ 0.9178 │ 0.8446 │ 0.8576 │ 0.9060 │ 0.9071 │ 0.9049 │ 0.7560 │ 0.9217 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7907 │ 0.8576 │ 0.9060 │    0.9071 │ 0.9049 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 29: 100%|██████████| 153/153 [03:14<00:00,  0.79it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.740, val/mAP_50_95=0.791, val/mAP_50=0.918, val/ema_mAP_50_95=0.803, val/F1=0.906, train/loss=5.790]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7875 │ 0.9104 │ 0.8427 │ 0.8554 │ 0.9027 │ 0.9075 │ 0.8979 │ 0.7471 │ 0.9207 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7875 │ 0.8554 │ 0.9027 │    0.9075 │ 0.8979 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 30: 100%|██████████| 153/153 [03:17<00:00,  0.78it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.880, val/mAP_50_95=0.788, val/mAP_50=0.910, val/ema_mAP_50_95=0.800, val/F1=0.903, train/loss=5.710]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7883 │ 0.9073 │ 0.8483 │ 0.8573 │ 0.8982 │ 0.9008 │ 0.8955 │ 0.7496 │ 0.9180 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7883 │ 0.8573 │ 0.8982 │    0.9008 │ 0.8955 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 31: 100%|██████████| 153/153 [03:01<00:00,  0.84it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.960, val/mAP_50_95=0.788, val/mAP_50=0.907, val/ema_mAP_50_95=0.800, val/F1=0.898, train/loss=5.780]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7681 │ 0.8997 │ 0.8235 │ 0.8450 │ 0.8877 │ 0.8669 │ 0.9096 │ 0.7294 │ 0.9082 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7681 │ 0.8450 │ 0.8877 │    0.8669 │ 0.9096 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 32: 100%|██████████| 153/153 [03:20<00:00,  0.76it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.210, val/mAP_50_95=0.768, val/mAP_50=0.900, val/ema_mAP_50_95=0.796, val/F1=0.888, train/loss=5.630]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7864 │ 0.9082 │ 0.8418 │ 0.8612 │ 0.8950 │ 0.8798 │ 0.9108 │ 0.7489 │ 0.9128 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7864 │ 0.8612 │ 0.8950 │    0.8798 │ 0.9108 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 33: 100%|██████████| 153/153 [03:05<00:00,  0.83it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.900, val/mAP_50_95=0.786, val/mAP_50=0.908, val/ema_mAP_50_95=0.795, val/F1=0.895, train/loss=5.690]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7831 │ 0.9120 │ 0.8354 │ 0.8567 │ 0.8999 │ 0.8871 │ 0.9131 │ 0.7458 │ 0.9167 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7831 │ 0.8567 │ 0.8999 │    0.8871 │ 0.9131 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 34: 100%|██████████| 153/153 [03:28<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.100, val/mAP_50_95=0.783, val/mAP_50=0.912, val/ema_mAP_50_95=0.796, val/F1=0.900, train/loss=5.780]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7803 │ 0.9078 │ 0.8340 │ 0.8546 │ 0.8966 │ 0.8976 │ 0.8955 │ 0.7390 │ 0.9176 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7803 │ 0.8546 │ 0.8966 │    0.8976 │ 0.8955 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 35: 100%|██████████| 153/153 [03:13<00:00,  0.79it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.910, val/mAP_50_95=0.780, val/mAP_50=0.908, val/ema_mAP_50_95=0.793, val/F1=0.897, train/loss=5.430]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7861 │ 0.9182 │ 0.8501 │ 0.8595 │ 0.9017 │ 0.9269 │ 0.8779 │ 0.7439 │ 0.9226 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7861 │ 0.8595 │ 0.9017 │    0.9269 │ 0.8779 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 36: 100%|██████████| 153/153 [03:08<00:00,  0.81it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.580, val/mAP_50_95=0.786, val/mAP_50=0.918, val/ema_mAP_50_95=0.789, val/F1=0.902, train/loss=5.610]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7875 │ 0.9155 │ 0.8412 │ 0.8575 │ 0.8988 │ 0.9068 │ 0.8908 │ 0.7574 │ 0.9243 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7875 │ 0.8575 │ 0.8988 │    0.9068 │ 0.8908 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 37: 100%|██████████| 153/153 [03:11<00:00,  0.80it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.550, val/mAP_50_95=0.787, val/mAP_50=0.916, val/ema_mAP_50_95=0.794, val/F1=0.899, train/loss=5.860]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7717 │ 0.9149 │ 0.8404 │ 0.8414 │ 0.8940 │ 0.9070 │ 0.8815 │ 0.7518 │ 0.9205 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7717 │ 0.8414 │ 0.8940 │    0.9070 │ 0.8815 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 38: 100%|██████████| 153/153 [03:25<00:00,  0.74it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.900, val/mAP_50_95=0.772, val/mAP_50=0.915, val/ema_mAP_50_95=0.793, val/F1=0.894, train/loss=5.900]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7560 │ 0.9127 │ 0.8409 │ 0.8258 │ 0.8987 │ 0.9019 │ 0.8955 │ 0.7469 │ 0.9192 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7560 │ 0.8258 │ 0.8987 │    0.9019 │ 0.8955 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 39: 100%|██████████| 153/153 [03:23<00:00,  0.75it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=7.150, val/mAP_50_95=0.756, val/mAP_50=0.913, val/ema_mAP_50_95=0.791, val/F1=0.899, train/loss=5.560]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7888 │ 0.9133 │ 0.8348 │ 0.8552 │ 0.9007 │ 0.9071 │ 0.8944 │ 0.7525 │ 0.9213 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7888 │ 0.8552 │ 0.9007 │    0.9071 │ 0.8944 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 40: 100%|██████████| 153/153 [03:38<00:00,  0.70it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.720, val/mAP_50_95=0.789, val/mAP_50=0.913, val/ema_mAP_50_95=0.793, val/F1=0.901, train/loss=5.540]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7965 │ 0.9233 │ 0.8548 │ 0.8633 │ 0.9013 │ 0.9024 │ 0.9002 │ 0.7677 │ 0.9243 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7965 │ 0.8633 │ 0.9013 │    0.9024 │ 0.9002 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 41: 100%|██████████| 153/153 [03:29<00:00,  0.73it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.410, val/mAP_50_95=0.797, val/mAP_50=0.923, val/ema_mAP_50_95=0.796, val/F1=0.901, train/loss=5.480]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7836 │ 0.9118 │ 0.8393 │ 0.8512 │ 0.8945 │ 0.9031 │ 0.8862 │ 0.7448 │ 0.9184 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7836 │ 0.8512 │ 0.8945 │    0.9031 │ 0.8862 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 42: 100%|██████████| 153/153 [03:22<00:00,  0.76it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.800, val/mAP_50_95=0.784, val/mAP_50=0.912, val/ema_mAP_50_95=0.793, val/F1=0.895, train/loss=5.310]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7838 │ 0.9076 │ 0.8376 │ 0.8540 │ 0.9003 │ 0.8946 │ 0.9061 │ 0.7560 │ 0.9184 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7838 │ 0.8540 │ 0.9003 │    0.8946 │ 0.9061 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 43: 100%|██████████| 153/153 [03:05<00:00,  0.83it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.880, val/mAP_50_95=0.784, val/mAP_50=0.908, val/ema_mAP_50_95=0.795, val/F1=0.900, train/loss=5.460]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7892 │ 0.9072 │ 0.8395 │ 0.8601 │ 0.8926 │ 0.8875 │ 0.8979 │ 0.7511 │ 0.9166 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7892 │ 0.8601 │ 0.8926 │    0.8875 │ 0.8979 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 44: 100%|██████████| 153/153 [03:44<00:00,  0.68it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.870, val/mAP_50_95=0.789, val/mAP_50=0.907, val/ema_mAP_50_95=0.798, val/F1=0.893, train/loss=5.310]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7989 │ 0.9243 │ 0.8453 │ 0.8614 │ 0.8997 │ 0.9100 │ 0.8897 │ 0.7625 │ 0.9249 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7989 │ 0.8614 │ 0.8997 │    0.9100 │ 0.8897 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 45: 100%|██████████| 153/153 [03:43<00:00,  0.68it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.510, val/mAP_50_95=0.799, val/mAP_50=0.924, val/ema_mAP_50_95=0.797, val/F1=0.900, train/loss=5.390]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7872 │ 0.9154 │ 0.8382 │ 0.8542 │ 0.8977 │ 0.9096 │ 0.8862 │ 0.7615 │ 0.9292 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7872 │ 0.8542 │ 0.8977 │    0.9096 │ 0.8862 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 46: 100%|██████████| 153/153 [03:15<00:00,  0.78it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.630, val/mAP_50_95=0.787, val/mAP_50=0.915, val/ema_mAP_50_95=0.801, val/F1=0.898, train/loss=5.450]

                              Val — Overall Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃           mAP            ┃  mAR   ┃         F1 sweep         ┃     segm mAP    ┃
┡━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━╇━━━━━━━━┯━━━━━━━━┯━━━━━━━━╇━━━━━━━━┯━━━━━━━━┩
│ 50:95  │   50   │   75   │  @500  │   F1   │  Prec  │ Recall │ 50:95  │   50   │
├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0.7932 │ 0.9147 │ 0.8388 │ 0.8597 │ 0.8924 │ 0.8988 │ 0.8862 │ 0.7630 │ 0.9211 │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

                       Val — Per-class Metrics
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Class           ┃ AP 50:95 ┃     AR ┃     F1 ┃ Precision ┃ Recall ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ microcotiledone │   0.7932 │ 0.8597 │ 0.8924 │    0.8988 │ 0.8862 │
└─────────────────┴──────────┴────────┴────────┴───────────┴────────┘

Epoch 46: 100%|██████████| 153/153 [03:33<00:00,  0.72it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.760, val/mAP_50_95=0.793, val/mAP_50=0.915, val/ema_mAP_50_95=0.801, val/F1=0.892, train/loss=5.450]

Monitored metric __rfdetr_effective_map__ did not improve in the last 30 records. Best score: 0.808. Signaling Trainer to stop.

Epoch 46: 100%|██████████| 153/153 [03:39<00:00,  0.70it/s, train/lr=0.0001, train/lr_min=3.23e-6, train/lr_max=0.0001, val/loss=6.760, val/mAP_50_95=0.793, val/mAP_50=0.915, val/ema_mAP_50_95=0.801, val/F1=0.892, train/loss=5.420]
[2026-03-28 21:24:04] [INFO] rf-detr - Best total checkpoint saved from regular (regular=0.8081, ema=0.8079)

In [7]:
from pathlib import Path
from rfdetr import RFDETRSegSmall

OUTPUT_DIR = Path(r"D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1").resolve()
DATASET_DIR = Path(r"D:\projeto_placentas_clayton\dataset_v2_coco_rf_detr").resolve()

ckpt = OUTPUT_DIR / "checkpoint_best_total.pth"
assert ckpt.is_file(), f"missing checkpoint: {ckpt} — run training cell first"

infer_model = RFDETRSegSmall(pretrain_weights=str(ckpt))

valid_imgs = sorted((DATASET_DIR / "valid").glob("*.jpg"))
if not valid_imgs:
    valid_imgs = sorted((DATASET_DIR / "valid").glob("*.png"))
assert valid_imgs, "no jpg/png in valid/"

sample = valid_imgs[0]
detections = infer_model.predict(str(sample), threshold=0.5)
print("sample:", sample.name)
print(detections)

[2026-03-30 21:39:18] [WARNING] rf-detr - Using a different number of positional encodings than DINOv2, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.
[2026-03-30 21:39:18] [WARNING] rf-detr - Using patch size 12 instead of 14, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.
[2026-03-30 21:39:22] [WARNING] rf-detr - Model is not optimized for inference. Latency may be higher than expected. You can optimize the model for inference by calling model.optimize_for_inference().
`use_return_dict` is deprecated! Use `return_dict` instead!

sample: ROSILHA-M-B_003_jpg.rf.863a24cebe30a134937348de5cbcaa87.jpg
Detections(xyxy=array([[ 1.53435379e+02, -2.62222290e-01,  2.93127350e+02,
         2.07700958e+02],
       [ 1.49295568e+01,  1.65860580e+02,  1.58001694e+02,
         2.79225983e+02],
       [ 9.37325134e+01,  2.76210876e+02,  1.92140076e+02,
         3.54744263e+02],
       [ 2.90781586e+02, -7.28063583e-01,  4.47627716e+02,
         1.96830627e+02],
       [ 4.50275513e+02, -3.83005142e-01,  5.83812500e+02,
         1.84177216e+02],
       [ 3.11546326e-01,  3.07515991e+02,  8.52101822e+01,
         3.91211273e+02],
       [ 5.41188660e+02,  4.74656799e+02,  5.92676392e+02,
         5.15623230e+02],
       [ 3.89480347e+02,  1.24965134e+02,  4.46802063e+02,
         1.94998352e+02],
       [ 3.35158813e+02,  1.52360901e+02,  3.84799530e+02,
         2.31628784e+02],
       [ 6.03294373e-02,  1.07045174e-01,  1.29572464e+02,
         1.22521591e+02],
       [ 1.89579483e+02,  2.33180466e+02,  5.61032593e+02,
         4.26671143e+02],
       [ 1.75843201e+02,  4.31531189e+02,  2.53335953e+02,
         5.49686646e+02],
       [ 1.26648331e+02,  3.86787653e-01,  1.82670883e+02,
         2.50688133e+01],
       [-9.26470757e-02,  1.21267975e+02,  5.00621033e+01,
         1.77718048e+02],
       [ 4.69073853e+02,  6.02009399e+02,  6.31004089e+02,
         6.40032288e+02],
       [ 2.34298065e+02,  5.16699524e+02,  4.52729065e+02,
         6.40142883e+02],
       [ 2.19238586e+02,  6.06039185e+02,  2.70901855e+02,
         6.39447937e+02],
       [-9.08613205e-02,  5.59299072e+02,  1.15123077e+02,
         6.39843628e+02],
       [ 3.89768372e+02,  4.22116150e+02,  5.07475342e+02,
         5.19052795e+02],
       [-2.55765915e-01,  3.65024261e+02,  1.72352448e+02,
         6.39975281e+02]], dtype=float32), mask=array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       ...,

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]]],
      shape=(20, 640, 640)), confidence=array([0.97033644, 0.9649949 , 0.96032053, 0.9594009 , 0.952081  ,
       0.94383776, 0.9377759 , 0.92887646, 0.9058385 , 0.8968834 ,
       0.89408773, 0.8541649 , 0.79076296, 0.7681186 , 0.6298849 ,
       0.62625086, 0.5834146 , 0.5662474 , 0.5192037 , 0.5122407 ],
      dtype=float32), class_id=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), tracker_id=None, data={}, metadata={})

## Post-training validation (RF-DETR)

Mirrors the YOLO validation style with RF-DETR-compatible checks:
- confidence sweep to find best F1 operating point
- per-image merged-mask IoU and optional visual overlays
- per-instance TP/FP/FN report with area error statistics

In [1]:
import json
from pathlib import Path

import cv2
import numpy as np
import pandas as pd

from rfdetr import RFDETRSegSmall

# Paths (reuse if already defined above)
if "DATASET_DIR" not in globals():
    DATASET_DIR = Path(r"D:\projeto_placentas_clayton\dataset_v2_coco_rf_detr").resolve()
if "OUTPUT_DIR" not in globals():
    OUTPUT_DIR = Path(r"D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1").resolve()

CKPT_PATH = OUTPUT_DIR / "checkpoint_best_total.pth"
assert CKPT_PATH.is_file(), f"missing checkpoint: {CKPT_PATH}"

ANN_PATH = DATASET_DIR / "valid" / "_annotations.coco.json"
assert ANN_PATH.is_file(), f"missing COCO annotations: {ANN_PATH}"

with ANN_PATH.open("r", encoding="utf-8") as f:
    coco = json.load(f)

images = coco.get("images", [])
annotations = coco.get("annotations", [])

img_by_id = {int(im["id"]): im for im in images}
anns_by_img = {}
for ann in annotations:
    anns_by_img.setdefault(int(ann["image_id"]), []).append(ann)

# Keep only images that physically exist in valid/
valid_img_paths = []
for im in images:
    p = DATASET_DIR / "valid" / im["file_name"]
    if p.is_file():
        valid_img_paths.append(p)

assert valid_img_paths, "No validation images found in DATASET_DIR/valid"

print(f"Validation images found: {len(valid_img_paths)}")
print(f"Validation annotations: {len(annotations)}")


def ann_to_mask(ann, height, width):
    """Convert COCO annotation segmentation to binary mask."""
    seg = ann.get("segmentation", None)
    if seg is None:
        return np.zeros((height, width), dtype=np.uint8)

    # Polygon format
    if isinstance(seg, list):
        mask = np.zeros((height, width), dtype=np.uint8)
        for poly in seg:
            if not poly or len(poly) < 6:
                continue
            pts = np.array(poly, dtype=np.float32).reshape(-1, 2)
            cv2.fillPoly(mask, [pts.astype(np.int32)], 1)
        return mask

    # RLE format (fallback if present)
    if isinstance(seg, dict):
        try:
            from pycocotools import mask as mask_utils

            return mask_utils.decode(seg).astype(np.uint8)
        except Exception:
            return np.zeros((height, width), dtype=np.uint8)

    return np.zeros((height, width), dtype=np.uint8)


def get_gt_masks_for_image(img_id):
    im = img_by_id[int(img_id)]
    h, w = int(im["height"]), int(im["width"])
    masks = [ann_to_mask(a, h, w) for a in anns_by_img.get(int(img_id), [])]
    return masks, h, w


def get_pred_masks_and_conf(det):
    masks = []
    confs = []

    pred_mask = getattr(det, "mask", None)
    pred_conf = getattr(det, "confidence", None)

    if pred_mask is not None:
        arr = np.asarray(pred_mask)
        if arr.ndim == 2:
            arr = arr[None, ...]
        for m in arr:
            masks.append((m > 0).astype(np.uint8))

    if pred_conf is not None:
        confs = list(np.asarray(pred_conf, dtype=np.float32))

    # If confidence array is missing/mismatched, fallback to all ones
    if len(confs) != len(masks):
        confs = [1.0] * len(masks)

    return masks, confs


def iou_binary(a, b):
    inter = np.logical_and(a > 0, b > 0).sum()
    union = np.logical_or(a > 0, b > 0).sum()
    return float(inter / union) if union > 0 else 0.0


def greedy_match(pred_masks, gt_masks, iou_thr=0.5):
    n_p, n_g = len(pred_masks), len(gt_masks)
    if n_p == 0 or n_g == 0:
        return []

    mat = np.zeros((n_p, n_g), dtype=np.float32)
    for i, pm in enumerate(pred_masks):
        for j, gm in enumerate(gt_masks):
            mat[i, j] = iou_binary(pm, gm)

    matched_p, matched_g = set(), set()
    pairs = []

    order = np.argsort(-mat, axis=None)
    pi, gi = np.unravel_index(order, mat.shape)

    for p_idx, g_idx in zip(pi, gi):
        if p_idx in matched_p or g_idx in matched_g:
            continue
        val = float(mat[p_idx, g_idx])
        if val < iou_thr:
            break
        pairs.append((p_idx, g_idx, val))
        matched_p.add(p_idx)
        matched_g.add(g_idx)

    return pairs


infer_model = RFDETRSegSmall(pretrain_weights=str(CKPT_PATH))
infer_model.optimize_for_inference()
print("RF-DETR loaded and optimized for inference.")

d:\miniconda3\envs\projeto_placentas\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[2026-04-04 14:57:09] [WARNING] rf-detr - Using a different number of positional encodings than DINOv2, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.
[2026-04-04 14:57:09] [WARNING] rf-detr - Using patch size 12 instead of 14, which means we're not loading DINOv2 backbone weights. This is not a problem if finetuning a pretrained RF-DETR model.

Validation images found: 27
Validation annotations: 852

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\backbone\dinov2.py:212: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[2] % block_size == 0 and x.shape[3] % block_size == 0, (
`use_return_dict` is deprecated! Use `return_dict` instead!
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\backbone\dinov2_with_windowed_attn.py:313: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_channels != self.num_channels:
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\backbone\dinov2.py:201: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_patches == num_positions and height == width:
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\transformer.py:285: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  topk = min(self.num_queries, enc_outputs_class_unselected_gidx.shape[-2])
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\transformer.py:57: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pos_tensor.size(-1) == 2:
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\transformer.py:59: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif pos_tensor.size(-1) == 4:
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\ops\modules\ms_deform_attn.py:127: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (input_spatial_shapes[:, 0] * input_spatial_shapes[:, 1]).sum() == Len_in
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\ops\modules\ms_deform_attn.py:137: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\ops\modules\ms_deform_attn.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif reference_points.shape[-1] == 4:
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\ops\functions\ms_deform_attn_func.py:30: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  value_list = value.split([H * W for H, W in value_spatial_shapes], dim=3)
d:\miniconda3\envs\projeto_placentas\lib\site-packages\rfdetr\models\ops\functions\ms_deform_attn_func.py:33: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for lid_, (H, W) in enumerate(value_spatial_shapes):

RF-DETR loaded and optimized for inference.

In [2]:
# 1) Confidence sweep (YOLO-like "optimal confidence" and F1)

IOU_THRESHOLD = 0.5
CONF_GRID = np.round(np.linspace(0.10, 0.90, 17), 3)

sweep_rows = []

for conf_thr in CONF_GRID:
    total_tp = total_fp = total_fn = 0
    tp_ious = []
    image_ious = []

    for img_path in valid_img_paths:
        img_name = img_path.name

        # Find image_id from COCO by filename
        img_id = None
        for k, im in img_by_id.items():
            if im.get("file_name") == img_name:
                img_id = int(k)
                break
        if img_id is None:
            continue

        gt_masks, h, w = get_gt_masks_for_image(img_id)

        det = infer_model.predict(str(img_path), threshold=float(conf_thr))
        pred_masks, pred_confs = get_pred_masks_and_conf(det)

        # Keep explicit thresholding by confidence for safety
        pred_masks = [m for m, c in zip(pred_masks, pred_confs) if c >= conf_thr]

        # Resize predictions if needed to GT shape
        resized_preds = []
        for pm in pred_masks:
            if pm.shape != (h, w):
                pm = cv2.resize(pm.astype(np.uint8), (w, h), interpolation=cv2.INTER_NEAREST)
            resized_preds.append((pm > 0).astype(np.uint8))
        pred_masks = resized_preds

        pairs = greedy_match(pred_masks, gt_masks, iou_thr=IOU_THRESHOLD)

        tp = len(pairs)
        fp = len(pred_masks) - tp
        fn = len(gt_masks) - tp

        total_tp += tp
        total_fp += fp
        total_fn += fn

        tp_ious.extend([p[2] for p in pairs])

        gt_union = np.zeros((h, w), dtype=np.uint8)
        for gm in gt_masks:
            gt_union = np.logical_or(gt_union, gm).astype(np.uint8)

        pred_union = np.zeros((h, w), dtype=np.uint8)
        for pm in pred_masks:
            pred_union = np.logical_or(pred_union, pm).astype(np.uint8)

        image_ious.append(iou_binary(gt_union, pred_union))

    precision = total_tp / (total_tp + total_fp) if (total_tp + total_fp) else 0.0
    recall = total_tp / (total_tp + total_fn) if (total_tp + total_fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    sweep_rows.append(
        {
            "conf": float(conf_thr),
            "tp": int(total_tp),
            "fp": int(total_fp),
            "fn": int(total_fn),
            "precision": float(precision),
            "recall": float(recall),
            "f1": float(f1),
            "mean_iou_tp": float(np.mean(tp_ious)) if tp_ious else 0.0,
            "mean_iou_image_union": float(np.mean(image_ious)) if image_ious else 0.0,
        }
    )

sweep_df = pd.DataFrame(sweep_rows).sort_values("conf").reset_index(drop=True)
BEST_ROW = sweep_df.loc[sweep_df["f1"].idxmax()]
BEST_CONF = float(BEST_ROW["conf"])

print("\n" + "=" * 60)
print("RF-DETR VALIDATION (confidence sweep)")
print("=" * 60)
print(f"Best confidence:      {BEST_CONF:.3f}")
print(f"Peak F1:              {BEST_ROW['f1']:.4f}")
print(f"Precision @best:      {BEST_ROW['precision']:.4f}")
print(f"Recall @best:         {BEST_ROW['recall']:.4f}")
print(f"TP/FP/FN @best:       {int(BEST_ROW['tp'])}/{int(BEST_ROW['fp'])}/{int(BEST_ROW['fn'])}")
print(f"Mean IoU (TP pairs):  {BEST_ROW['mean_iou_tp']:.4f}")
print(f"Mean IoU (union/img): {BEST_ROW['mean_iou_image_union']:.4f}")
print("=" * 60)

SWEEP_CSV = OUTPUT_DIR / "validation_conf_sweep_rfdetr.csv"
sweep_df.to_csv(SWEEP_CSV, index=False)
print(f"Sweep table saved to: {SWEEP_CSV}")

display(sweep_df)

============================================================
RF-DETR VALIDATION (confidence sweep)
============================================================
Best confidence:      0.500
Peak F1:              0.8955
Precision @best:      0.9113
Recall @best:         0.8803
TP/FP/FN @best:       750/73/102
Mean IoU (TP pairs):  0.9020
Mean IoU (union/img): 0.8847
============================================================
Sweep table saved to: D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\validation_conf_sweep_rfdetr.csv

,conf,tp,fp,fn,precision,recall,f1,mean_iou_tp,mean_iou_image_union
0,0.10,818,689,34,0.542800,0.960094,0.693514,0.908161,0.936042
1,0.15,816,507,36,0.616780,0.957746,0.750345,0.908201,0.936404
2,0.20,812,402,40,0.668863,0.953052,0.786060,0.907665,0.937087
3,0.25,808,326,44,0.712522,0.948357,0.813696,0.906969,0.936953
4,0.30,805,253,47,0.760870,0.944836,0.842932,0.905591,0.936550
5,0.35,796,200,56,0.799197,0.934272,0.861472,0.905553,0.936429
6,0.40,785,149,67,0.840471,0.921362,0.879059,0.905268,0.932261
7,0.45,770,99,82,0.886076,0.903756,0.894829,0.902168,0.911527
8,0.50,750,73,102,0.911300,0.880282,0.895522,0.902001,0.884661
9,0.55,726,52,126,0.933162,0.852113,0.890798,0.902876,0.840435
10,0.60,696,39,156,0.946939,0.816901,0.877127,0.907446,0.800474
11,0.65,672,33,180,0.953191,0.788732,0.863198,0.912011,0.776299
12,0.70,648,26,204,0.961424,0.760563,0.849279,0.915512,0.743832
13,0.75,620,19,232,0.970266,0.727700,0.831657,0.918742,0.719386
14,0.80,586,15,266,0.975042,0.687793,0.806607,0.922034,0.685775
15,0.85,548,10,304,0.982079,0.643192,0.777305,0.926372,0.651146
16,0.90,453,7,399,0.984783,0.531690,0.690549,0.931964,0.554673

In [3]:
# 2) Per-image merged-mask IoU + visual overlays (GT=green, AI=red, overlap=yellow)

import matplotlib.pyplot as plt

VIZ_DIR = OUTPUT_DIR / "validation_iou_viz_rfdetr"
VIZ_DIR.mkdir(parents=True, exist_ok=True)

per_image_rows = []

for img_path in valid_img_paths:
    img_name = img_path.name

    img_id = None
    for k, im in img_by_id.items():
        if im.get("file_name") == img_name:
            img_id = int(k)
            break
    if img_id is None:
        continue

    gt_masks, h, w = get_gt_masks_for_image(img_id)

    det = infer_model.predict(str(img_path), threshold=float(BEST_CONF))
    pred_masks, pred_confs = get_pred_masks_and_conf(det)
    pred_masks = [m for m, c in zip(pred_masks, pred_confs) if c >= BEST_CONF]

    # Normalize mask shape to GT size
    norm_pred = []
    for pm in pred_masks:
        if pm.shape != (h, w):
            pm = cv2.resize(pm.astype(np.uint8), (w, h), interpolation=cv2.INTER_NEAREST)
        norm_pred.append((pm > 0).astype(np.uint8))
    pred_masks = norm_pred

    gt_union = np.zeros((h, w), dtype=np.uint8)
    for gm in gt_masks:
        gt_union = np.logical_or(gt_union, gm).astype(np.uint8)

    pred_union = np.zeros((h, w), dtype=np.uint8)
    for pm in pred_masks:
        pred_union = np.logical_or(pred_union, pm).astype(np.uint8)

    iou = iou_binary(gt_union, pred_union)
    per_image_rows.append({"image": img_name, "iou_union": iou, "n_gt": len(gt_masks), "n_pred": len(pred_masks)})

    # Render visualization
    img_bgr = cv2.imread(str(img_path))
    if img_bgr is None:
        continue
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    if img_rgb.shape[:2] != (h, w):
        img_rgb = cv2.resize(img_rgb, (w, h), interpolation=cv2.INTER_LINEAR)

    overlay = img_rgb.copy()
    overlay[gt_union == 1] = (overlay[gt_union == 1] * 0.5 + np.array([0, 255, 0]) * 0.5).astype(np.uint8)
    overlay[pred_union == 1] = (overlay[pred_union == 1] * 0.5 + np.array([255, 0, 0]) * 0.5).astype(np.uint8)
    overlap = np.logical_and(gt_union, pred_union)
    overlay[overlap] = (overlay[overlap] * 0.5 + np.array([255, 255, 0]) * 0.5).astype(np.uint8)

    diff = np.zeros((h, w, 3), dtype=np.uint8)
    diff[gt_union == 1] = [0, 200, 0]
    diff[pred_union == 1] = [200, 0, 0]
    diff[overlap] = [255, 255, 0]

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle(f"{img_name} | IoU={iou:.3f} | GT={len(gt_masks)} | Pred={len(pred_masks)}", fontsize=12)
    axes[0].imshow(img_rgb); axes[0].set_title("Original"); axes[0].axis("off")
    axes[1].imshow(overlay); axes[1].set_title("GT=green  AI=red  Overlap=yellow"); axes[1].axis("off")
    axes[2].imshow(diff); axes[2].set_title("Difference map"); axes[2].axis("off")
    plt.tight_layout()
    plt.savefig(VIZ_DIR / f"iou_viz_{Path(img_name).stem}.png", dpi=140, bbox_inches="tight")
    plt.close(fig)

    print(f"{img_name:45s} IoU={iou:.4f}")

per_image_df = pd.DataFrame(per_image_rows).sort_values("iou_union")
PER_IMAGE_CSV = OUTPUT_DIR / "validation_per_image_iou_rfdetr.csv"
per_image_df.to_csv(PER_IMAGE_CSV, index=False)

print("\nSaved:")
print("-", VIZ_DIR)
print("-", PER_IMAGE_CSV)
print(f"Mean per-image union IoU: {per_image_df['iou_union'].mean():.4f}")
display(per_image_df)

ROSILHA-M-G_005_jpg.rf.afae2fb85329c0fe56679d51ca1c64fd.jpg IoU=0.8687
ZAZA-G_010_jpg.rf.cd14098445a0a54c10014aaa7d8f975c.jpg IoU=0.9394
ZAINA-679-B_010_jpg.rf.4a3c6644c7fdcdc349eacebe9a97fbd7.jpg IoU=0.9257
TP-B_001_jpg.rf.476ac40460a2659ffbad7973abf99d86.jpg IoU=0.9495
ROSILHA-M-G_017_jpg.rf.85fc7b8a7b63a2cbb64907a1c82d5d51.jpg IoU=0.9321
TORDILHA-B_009_jpg.rf.5902113a7929ec9592dc2b09471de461.jpg IoU=0.8935
ROSILHA-M-D_009_jpg.rf.b52035c8fe5fd87e1eed76dc4bbe6a14.jpg IoU=0.9503
TORDILHA-D_006_jpg.rf.d879d44ef1add0b327aa39f6650afc47.jpg IoU=0.7485
ZAINA-679-B_011_jpg.rf.27d46a055eff6f5810ec4c5c9429b994.jpg IoU=0.9628
ZAZA-B_008_jpg.rf.92ad451b5359143319a46e599a0239d1.jpg IoU=0.8894
ROSILHA-M-G_001_jpg.rf.3dab74a9f6c203f6aca8afc07a353bd2.jpg IoU=0.8873
TORDILHA-B_010_jpg.rf.698124083a3806b10e86f6304c2b5ce1.jpg IoU=0.9406
TOSTADA-G_011_jpg.rf.c0b219a9a6742c565eddfcdb51541b7d.jpg IoU=0.9488
ROSILHA-M-B_003_jpg.rf.863a24cebe30a134937348de5cbcaa87.jpg IoU=0.9064
ZAZA-G_012_jpg.rf.b65fca463e4411032a599acd7494f06d.jpg IoU=0.9198
TORDILHA-G_009_jpg.rf.b279af9f6892d54790621c0f5458daf3.jpg IoU=0.7669
TP-G_010_jpg.rf.5c8b394cdec2d68bae00b4eb6679ec08.jpg IoU=0.8111
TOSTADA-B_006_jpg.rf.fd9a20fd791843647a700cdeb77e0cc3.jpg IoU=0.8413
TP-D_010_jpg.rf.8e807d0647c50bd1b8d28134da2e26a4.jpg IoU=0.9395
TP-G_008_jpg.rf.7ce2f84776589571f8d07c60f1c4e63c.jpg IoU=0.9437
ZAZA-D_004_jpg.rf.02ed2d595bd7bc4d5f40bda7d3f8e5d2.jpg IoU=0.8906
ROSILHA-M-B_009_jpg.rf.d2aa8881a0b4f54b4bdb89392b953e71.jpg IoU=0.6661
TORDILHA-B_012_jpg.rf.0b5caafb1952d960be9aa54f5506bf96.jpg IoU=0.9205
ROSILHA-M-D_006_jpg.rf.de71085683e9c7eb460be0f184fb31ac.jpg IoU=0.9110
TOSTADA-B_003_jpg.rf.ef070508fe8cf028db79cd03961c37d8.jpg IoU=0.8471
TORDILHA-D_001_jpg.rf.36e39c15aad81283f9bcc0f8afcd649f.jpg IoU=0.7477
TOSTADA-G_009_jpg.rf.506f019d1e54427e5f81510789439725.jpg IoU=0.9375

Saved:
- D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\validation_iou_viz_rfdetr
- D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\validation_per_image_iou_rfdetr.csv
Mean per-image union IoU: 0.8847

                                                image  iou_union  n_gt  n_pred
21  ROSILHA-M-B_009_jpg.rf.d2aa8881a0b4f54b4bdb893...   0.666077    44      38
25  TORDILHA-D_001_jpg.rf.36e39c15aad81283f9bcc0f8...   0.747669    24      23
7   TORDILHA-D_006_jpg.rf.d879d44ef1add0b327aa39f6...   0.748498    35      34
15  TORDILHA-G_009_jpg.rf.b279af9f6892d54790621c0f...   0.766863    37      36
16  TP-G_010_jpg.rf.5c8b394cdec2d68bae00b4eb6679ec...   0.811115    37      34
17  TOSTADA-B_006_jpg.rf.fd9a20fd791843647a700cdeb...   0.841324    24      25
24  TOSTADA-B_003_jpg.rf.ef070508fe8cf028db79cd039...   0.847116    26      27
0   ROSILHA-M-G_005_jpg.rf.afae2fb85329c0fe56679d5...   0.868735    13      12
10  ROSILHA-M-G_001_jpg.rf.3dab74a9f6c203f6aca8afc...   0.887320    18      19
9   ZAZA-B_008_jpg.rf.92ad451b5359143319a46e599a02...   0.889363    28      26
20  ZAZA-D_004_jpg.rf.02ed2d595bd7bc4d5f40bda7d3f8...   0.890572    35      32
5   TORDILHA-B_009_jpg.rf.5902113a7929ec9592dc2b09...   0.893541    48      49
13  ROSILHA-M-B_003_jpg.rf.863a24cebe30a134937348d...   0.906447    20      20
23  ROSILHA-M-D_006_jpg.rf.de71085683e9c7eb460be0f...   0.910987    39      34
14  ZAZA-G_012_jpg.rf.b65fca463e4411032a599acd7494...   0.919751    35      31
22  TORDILHA-B_012_jpg.rf.0b5caafb1952d960be9aa54f...   0.920530    41      42
2   ZAINA-679-B_010_jpg.rf.4a3c6644c7fdcdc349eaceb...   0.925738    38      42
4   ROSILHA-M-G_017_jpg.rf.85fc7b8a7b63a2cbb64907a...   0.932148    17      18
26  TOSTADA-G_009_jpg.rf.506f019d1e54427e5f8151078...   0.937514    42      40
1   ZAZA-G_010_jpg.rf.cd14098445a0a54c10014aaa7d8f...   0.939418    29      26
18  TP-D_010_jpg.rf.8e807d0647c50bd1b8d28134da2e26...   0.939488    47      46
11  TORDILHA-B_010_jpg.rf.698124083a3806b10e86f630...   0.940598    31      33
19  TP-G_008_jpg.rf.7ce2f84776589571f8d07c60f1c4e6...   0.943700    33      27
12  TOSTADA-G_011_jpg.rf.c0b219a9a6742c565eddfcdb5...   0.948773    30      31
3   TP-B_001_jpg.rf.476ac40460a2659ffbad7973abf99d...   0.949532    31      30
6   ROSILHA-M-D_009_jpg.rf.b52035c8fe5fd87e1eed76d...   0.950266    26      25
8   ZAINA-679-B_011_jpg.rf.27d46a055eff6f5810ec4c5...   0.962763    24      23

In [4]:
# 3) Per-instance TP/FP/FN report with area error stats (YOLO-like)

# Corrected 2026-09-07: anisotropic 4140x3096 -> 640x640 stretch; correction = 3096/4140 = 0.747826
AREA_FACTOR = (50.0 / 72.0) ** 2 * (3096.0 / 4140.0)  # same conversion used in YOLO notebooks
IOU_THRESHOLD = 0.5

rows = []

for img_path in valid_img_paths:
    img_name = img_path.name

    img_id = None
    for k, im in img_by_id.items():
        if im.get("file_name") == img_name:
            img_id = int(k)
            break
    if img_id is None:
        continue

    gt_masks, h, w = get_gt_masks_for_image(img_id)

    det = infer_model.predict(str(img_path), threshold=float(BEST_CONF))
    pred_masks, pred_confs = get_pred_masks_and_conf(det)
    pred_masks = [m for m, c in zip(pred_masks, pred_confs) if c >= BEST_CONF]

    norm_pred = []
    for pm in pred_masks:
        if pm.shape != (h, w):
            pm = cv2.resize(pm.astype(np.uint8), (w, h), interpolation=cv2.INTER_NEAREST)
        norm_pred.append((pm > 0).astype(np.uint8))
    pred_masks = norm_pred

    n_p, n_g = len(pred_masks), len(gt_masks)
    mat = np.zeros((n_p, n_g), dtype=np.float32)
    for i, pm in enumerate(pred_masks):
        for j, gm in enumerate(gt_masks):
            mat[i, j] = iou_binary(pm, gm)

    matched_p, matched_g = set(), set()
    if n_p > 0 and n_g > 0:
        order = np.argsort(-mat, axis=None)
        pi, gi = np.unravel_index(order, mat.shape)
        for p_idx, g_idx in zip(pi, gi):
            if p_idx in matched_p or g_idx in matched_g:
                continue
            iou_val = float(mat[p_idx, g_idx])
            if iou_val < IOU_THRESHOLD:
                break

            p_area = int(pred_masks[p_idx].sum())
            g_area = int(gt_masks[g_idx].sum())
            area_err_pct = ((p_area - g_area) / g_area * 100.0) if g_area > 0 else 0.0

            rows.append(
                {
                    "Image": img_name,
                    "Type": "TP",
                    "IoU": round(iou_val, 4),
                    "GT_Area_um2": round(g_area * AREA_FACTOR, 2),
                    "AI_Area_um2": round(p_area * AREA_FACTOR, 2),
                    "Area_Err_%": round(area_err_pct, 2),
                    "Abs_Area_Err_%": round(abs(area_err_pct), 2),
                }
            )
            matched_p.add(p_idx)
            matched_g.add(g_idx)

    # False positives
    for p_idx in range(n_p):
        if p_idx in matched_p:
            continue
        p_area = int(pred_masks[p_idx].sum())
        rows.append(
            {
                "Image": img_name,
                "Type": "FP",
                "IoU": 0.0,
                "GT_Area_um2": 0.0,
                "AI_Area_um2": round(p_area * AREA_FACTOR, 2),
                "Area_Err_%": np.nan,
                "Abs_Area_Err_%": np.nan,
            }
        )

    # False negatives
    for g_idx in range(n_g):
        if g_idx in matched_g:
            continue
        g_area = int(gt_masks[g_idx].sum())
        rows.append(
            {
                "Image": img_name,
                "Type": "FN",
                "IoU": 0.0,
                "GT_Area_um2": round(g_area * AREA_FACTOR, 2),
                "AI_Area_um2": 0.0,
                "Area_Err_%": np.nan,
                "Abs_Area_Err_%": np.nan,
            }
        )

report_df = pd.DataFrame(rows)

n_tp = int((report_df["Type"] == "TP").sum())
n_fp = int((report_df["Type"] == "FP").sum())
n_fn = int((report_df["Type"] == "FN").sum())

precision = n_tp / (n_tp + n_fp) if (n_tp + n_fp) else 0.0
recall = n_tp / (n_tp + n_fn) if (n_tp + n_fn) else 0.0

tp_df = report_df[report_df["Type"] == "TP"]
mean_iou = float(tp_df["IoU"].mean()) if len(tp_df) else 0.0
mean_gt = float(tp_df["GT_Area_um2"].mean()) if len(tp_df) else 0.0
mean_ai = float(tp_df["AI_Area_um2"].mean()) if len(tp_df) else 0.0
mean_err = float(tp_df["Area_Err_%"].mean()) if len(tp_df) else 0.0
mean_abs_err = float(tp_df["Abs_Area_Err_%"].mean()) if len(tp_df) else 0.0

REPORT_CSV = OUTPUT_DIR / "placenta_instance_report_rfdetr.csv"
report_df.to_csv(REPORT_CSV, index=False)

print("\n" + "=" * 55)
print("PER-INSTANCE REPORT (RF-DETR)")
print("=" * 55)
print(f"True Positives  (matched):      {n_tp}")
print(f"False Positives (extra preds):  {n_fp}")
print(f"False Negatives (missed GT):    {n_fn}")
print(f"Precision:                      {precision:.4f}")
print(f"Recall:                         {recall:.4f}")
print("-" * 55)
print(f"Mean IoU        (TP only):      {mean_iou:.4f}")
print(f"Mean GT Area    (TP only):      {mean_gt:.2f} µm²")
print(f"Mean AI Area    (TP only):      {mean_ai:.2f} µm²")
print(f"Mean Area Error (TP only):      {mean_err:.2f}%")
print(f"Mean Abs Error  (TP only):      {mean_abs_err:.2f}%")
print("=" * 55)
print(f"Report saved to: {REPORT_CSV}")

=======================================================
PER-INSTANCE REPORT (RF-DETR)
=======================================================
True Positives  (matched):      750
False Positives (extra preds):  73
False Negatives (missed GT):    102
Precision:                      0.9113
Recall:                         0.8803
-------------------------------------------------------
Mean IoU        (TP only):      0.9020
Mean GT Area    (TP only):      2380.92 µm²
Mean AI Area    (TP only):      2303.41 µm²
Mean Area Error (TP only):      -2.88%
Mean Abs Error  (TP only):      6.76%
=======================================================
Report saved to: D:\projeto_placentas_clayton\dev\projeto-placentas\v2_rf_detr\runs\seg_small_v1\placenta_instance_report_rfdetr.csv